package com.example.CarParkAPI.Models;

// TODO: fix the vehicle creation can this be a record if id is autogenerated?
public record Vehicle(
        String id,
        VehicleType type,
        String registration_plate,
        String cardNumber,
        String customerName,
        String customerEmail
){}
